import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useEffect } from 'react'

export default function Home() {

	// useEffect(() => {
	// 	document.body.style.overflow = "hidden"
	// 	window.addEventListener("mousemove" , (e) => {
	// 		if(e.pageX > 120 && e.pageX < 500 && document.getElementById("blob")){
	// 			document.getElementById("blob").style.marginLeft = (e.pageX-350)+"px"
	// 		}
	// 	})
	// })

	return (
		<>
		<Head>
			<title>Exponential Dev Studios© | Home</title>
			<meta name="description" content="Generated by create next app" />
			<meta name="viewport" content="width=device-width, initial-scale=1" />
			<link rel="icon" href="/favicon.ico" />
		</Head>

		<div className={styles.universal}>
			<video src='https://rejouice.com/videos/RJ-CONTACT-BG.webm' muted loop autoPlay ></video>

			<div>
			<h1 id='hero'>
				<br/>
				Exponential Design<br/>Studios.
				<span>
					<p>
					<br/>
					<br/>
						A team of passionate Software engineer's willing to
						revolutionize e-commerce industry with Ar-Vr technolgies.
					</p>
				</span>	
			</h1>
			</div>

		</div>

		</>
	)
}

// <div className={styles.main} >
			
// 			<section>

// 				<div className={styles.blob_container}>
// 					<video id='blob' src='https://rejouice.com/videos/RJ-BALL-BLUE-ORANGE.webm' muted loop autoPlay ></video>
// 				</div>


// 			</section>
			
// 		</div>